- name: Download Papertrail installer
  get_url:
    url: https://papertrailapp.com/destinations/3937483/setup.sh
    dest: /tmp/papertrailapp-setup.sh
    headers: "X-Papertrail-Token: {{papertrail_key}}"
  tags:
    - launch

- name: Execute Papertrail installer
  shell: sh /tmp/papertrailapp-setup.sh
  args:
    creates: "/usr/local/bin/remote_syslog"
  tags:
    - launch

- name: Configure rsyslog
  tags:
    - launch
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: '^\$LocalHostName '
    insertbefore: "^# rsyslog configuration file"
    line: "$LocalHostName {{domain}}"
    state: present
  notify: restart rsyslog

- name: Copy log_files
  tags:
    - launch
  template:
    src: ./templates/log_files.conf.j2
    dest: /etc/log_files.conf
    force: no
