- name: Ensure sudoers.d is enabled
  tags:
    - launch
  lineinfile:
    dest: /etc/sudoers
    regexp: '^#includedir /etc/sudoers.d'
    line: '#includedir /etc/sudoers.d'
    state: present
    backup: yes

- name: Set up password-less sudo for admin users
  tags:
    - launch
  copy:
    content: "%{{ssh_groups}} ALL=(ALL) NOPASSWD:ALL\nDefaults    env_keep+=SSH_AUTH_SOCK\n"
    dest: /etc/sudoers.d/admin
    owner: root
    group: root
    mode: 0440

- name: Strict SSH access
  tags:
    - launch
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^#?{{item.key}}'
    line: '{{item.key}} {{item.value}}'
    validate: '/usr/sbin/sshd -t -f %s'
  with_items:
    - { key: 'PermitRootLogin', value: 'yes'}
    - { key: 'PasswordAuthentication', value: 'no'}
    - { key: 'AllowGroups', value: '{{ssh_groups}} root' }
    - { key: 'MaxAuthTries', value: "5"}
    - { key: 'LoginGraceTime', value: "60"}
    - { key: 'MaxSessions', value: "5"}
    - { key: 'MaxStartups', value: "10:30:60"}
    - { key: 'Port', value: '{{ssh_port}}' }
  notify: restart sshd

- name: Configure firewall for SSH
  tags:
    - launch
  ufw: rule=allow port={{item}}
  with_items: "{{ufw_allow_ports}}"

- name: Enable firewall
  tags:
    - launch
  ufw: state=enabled
