- name: Create admin user
  tags:
    - launch
  user: >
    name="{{ssh_user}}"
    comment="Administrator account"
    state=present
    groups="{{ssh_groups}}"
    shell=/bin/bash
    append=yes
    createhome=yes

- name: Deploy ssh public key
  tags:
    - launch
  authorized_key:
    user: "{{ssh_user}}"
    key: "{{ssh_pub_key}}"
